version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "@me"
    assignees:
      - "@me"
    commit-message:
      prefix: "deps"
      include: "scope"
    ignore:
      # Ignore Node.js major version updates beyond v22
      - dependency-name: "node"
        versions: [">=23.0.0"]
